ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\dyk81\AppData\Roaming
CHROME_CRASHPAD_PIPE_NAME=\\.\pipe\crashpad_8376_OYOUJCWSROYIHFLJ
COMMONPROGRAMFILES=C:\Program Files\Common Files
COMMONPROGRAMFILES(X86)=C:\Program Files (x86)\Common Files
COMMONPROGRAMW6432=C:\Program Files\Common Files
COMPUTERNAME=DESKTOP-KJSVE6D
COMSPEC=C:\WINDOWS\system32\cmd.exe
DRIVERDATA=C:\Windows\System32\Drivers\DriverData
EFC_6732=1
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
HOMEDRIVE=C:
HOMEPATH=\Users\dyk81
IGCCSVC_DB=AQAAANCMnd8BFdERjHoAwE/Cl+sBAAAAgGcI66g4k0G6QU7+oUKwEQQAAAACAAAAAAAQZgAAAAEAACAAAACaOXVfy15P6/ebk3FLqylymve4rXmquoR0l098ViNfoAAAAAAOgAAAAAIAACAAAACA2ubPK8FTOp72sYKvXUJ7rqKU4HzmZw3L5upYCD/TZmAAAACb7R72nhrfbwKBxMafnzvqQbhMNmVAbk5w7o/aL3/GH4X1HvrJlTY6MOSbxx1jDZoVcwveSUfct2eINbIG77ftfOv4DoNvYewHawkAlBNhlbrfWFtq/z+FgBJR/ktK05RAAAAAJG6RTpgETCoESspq9DNwEdHL6ZaABN72M/UKpwxqVoWvEcww9DL/RJ3Rd8+YWQQEORmcYqYnwxsxakZh7e5QqQ==
JAVA_HOME=C:\Program Files\Java\jdk-11
LOCALAPPDATA=C:\Users\dyk81\AppData\Local
LOGONSERVER=\\DESKTOP-KJSVE6D
NUMBER_OF_PROCESSORS=20
ONEDRIVE=C:\Users\dyk81\OneDrive
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
OS=Windows_NT
PATH=C:\Program Files\Common Files\Oracle\Java\javapath;C:\Program Files\Java\jdk-11\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\bin;C:\Users\dyk81\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\dyk81\AppData\Local\Programs\Python\Python310\;C:\Users\dyk81\AppData\Local\Programs\Python\Python313\Scripts\;C:\Users\dyk81\AppData\Local\Programs\Python\Python313\;C:\Users\dyk81\AppData\Local\Microsoft\WindowsApps;C:\Users\dyk81\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\dyk81\AppData\Local\Programs\MiKTeX\miktex\bin\x64\;C:\Users\dyk81\AppData\Local\GitHubDesktop\bin;;C:\Program Files (x86)\ESTsoft\ALSee\x64
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=b701
PROGRAMDATA=C:\ProgramData
PROGRAMFILES=C:\Program Files
PROGRAMFILES(X86)=C:\Program Files (x86)
PROGRAMW6432=C:\Program Files
PSMODULEPATH=C:\Users\dyk81\Documents\WindowsPowerShell\Modules;C:\Program Files\WindowsPowerShell\Modules;C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SYSTEMDRIVE=C:
SYSTEMROOT=C:\WINDOWS
TEMP=C:\Users\dyk81\AppData\Local\Temp
TMP=C:\Users\dyk81\AppData\Local\Temp
TMPDIR=C:\Users\Public\Documents\ESTsoft\CreatorTemp
USERDOMAIN=DESKTOP-KJSVE6D
USERDOMAIN_ROAMINGPROFILE=DESKTOP-KJSVE6D
USERNAME=dyk81
USERPROFILE=C:\Users\dyk81
WINDIR=C:\WINDOWS
ZES_ENABLE_SYSMAN=1
TERM_PROGRAM=vscode
TERM_PROGRAM_VERSION=1.96.2
LANG=en_US.UTF-8
COLORTERM=truecolor
GIT_ASKPASS=c:\Users\dyk81\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass.sh
VSCODE_GIT_ASKPASS_NODE=C:\Users\dyk81\AppData\Local\Programs\Microsoft VS Code\Code.exe
VSCODE_GIT_ASKPASS_EXTRA_ARGS=
VSCODE_GIT_ASKPASS_MAIN=c:\Users\dyk81\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\git\dist\askpass-main.js
VSCODE_GIT_IPC_HANDLE=\\.\pipe\vscode-git-14d4131d3c-sock
KMA_SFCTM2_KEY=gW1elmiyQWWtXpZoslFl8w
VSCODE_ENV_REPLACE=KMA_SFCTM2_KEY=gW1elmiyQWWtXpZoslFl8w:PVAMOUNTBYPOWERGEN_KEY=eHgX5J93R2wPgAq/JUQzHP3xbkJ16lQIJXvQeY4fxh3EutJ9W/REVVrb84PbqmDitlWiLPtmcxDg8TqhaV0TlQ==:WIND_POWER_BY_HOUR_KEY=eHgX5J93R2wPgAq/JUQzHP3xbkJ16lQIJXvQeY4fxh3EutJ9W/REVVrb84PbqmDitlWiLPtmcxDg8TqhaV0TlQ==
PVAMOUNTBYPOWERGEN_KEY=eHgX5J93R2wPgAq/JUQzHP3xbkJ16lQIJXvQeY4fxh3EutJ9W/REVVrb84PbqmDitlWiLPtmcxDg8TqhaV0TlQ==
WIND_POWER_BY_HOUR_KEY=eHgX5J93R2wPgAq/JUQzHP3xbkJ16lQIJXvQeY4fxh3EutJ9W/REVVrb84PbqmDitlWiLPtmcxDg8TqhaV0TlQ==
VSCODE_INJECTION=1
VSCODE_NONCE=ed11fe3e-207e-46ce-afdb-c0a5ad29c526
VSCODE_STABLE=1
